### ISSUE TITLE
read_map() SuperDARNFieldMissingError

### ISSUE THREAD

**Issue by shibaji7** [SuperDARN/pydarn#122]
# BUG 

While accessing some of the map2 files I'm getting this error 

Error: The following fields in record 462 are missing: {'vector.mlat', 'vector.vel.median', 'vector.mlon', 'vector.kvect', 'vector.vel.sd', 'vector.channel', 'vector.index', 'vector.stid'}
Traceback (most recent call last):
  File "convert_map_to_csv.py", line 22, in read_map_files
    _md = reader.read_map()
  File "/home/shibaji/anaconda3/envs/collb/lib/python3.7/site-packages/pydarnio/dmap/superdarn.py", line 493, in read_map
    self._read_darn_records(file_struct_list)
  File "/home/shibaji/anaconda3/envs/collb/lib/python3.7/site-packages/pydarnio/dmap/superdarn.py", line 374, in _read_darn_records
    self._read_darn_record(format_fields)
  File "/home/shibaji/anaconda3/envs/collb/lib/python3.7/site-packages/pydarnio/dmap/superdarn.py", line 350, in _read_darn_record
    SDarnUtilities.missing_field_check(format_fields, record, self.rec_num)
  File "/home/shibaji/anaconda3/envs/collb/lib/python3.7/site-packages/pydarnio/dmap/superdarn.py", line 178, in missing_field_check
    SuperDARNFieldMissingError(rec_num, missing_fields)
pydarnio.exceptions.superdarn_exceptions.SuperDARNFieldMissingError: Error: The following fields in record 462 are missing: {'vector.mlat', 'vector.vel.median', 'vector.mlon', 'vector.kvect', 'vector.vel.sd', 'vector.channel', 'vector.index', 'vector.stid'}

File -  /sd-data/2012/map2/north/20120309.north.map2.bz2

**Comment by mts299** [comment]
What version of pyDARN are you using and this would be a pyDARNio problem now. We separated all IO functionality in the recent release

**Comment by mts299** [comment]
@shibaji7 side note to get around this you can use `read_dmap()` to read the file in the mean time

**Comment by mts299** [comment]
@shibaji7 I have fixed the problem on pyDARNio: https://github.com/SuperDARN/pyDARNio/pull/18

Please check it out to see if it works for you. 

closing this issue as it is on pyDARNio now.
