### ISSUE TITLE
Pathlib2 dependency missing from feature/borealis_conversion branch.

### ISSUE THREAD

**Issue by kkotyk** [SuperDARN/pydarn#21]
>>> import pydarn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/k2/Documents/superdarn_github/borealis/pydarn/pydarn/__init__.py", line 38, in <module>
    from .io.borealis.borealis import BorealisRead
  File "/home/k2/Documents/superdarn_github/borealis/pydarn/pydarn/io/borealis/borealis.py", line 49, in <module>
    from .borealis_site import BorealisSiteRead, BorealisSiteWrite
  File "/home/k2/Documents/superdarn_github/borealis/pydarn/pydarn/io/borealis/borealis_site.py", line 47, in <module>
    from pathlib2 import Path
ModuleNotFoundError: No module named 'pathlib2'

**Comment by mts299** [comment]
@kkotyk can you please comment this on the PR #16  so it can be addressed right away as the code has not been merged. So any issues with that branch should be placed in PR #16.
