### ISSUE TITLE
BUG: hdw repo not being cloned on install

### ISSUE THREAD

**Issue by carleyjmartin** [SuperDARN/pydarn#292]
# BUG 

I've had a few reports of the hdw repository not being downloaded on install. 
I can recreate this error, but only when trying to install system wide.

Until a solution is made I recommend that if you find this error you can try:
1. Installing and running pyDARN programs in a virtual environment https://docs.python.org/3/library/venv.html
2. Cloning the hdw repository in the `utils` directory of wherever pyDARN has installed https://github.com/SuperDARN/hdw

If you do find this error, please comment with the traceback, and so that I know if it's widespread or os dependent. 

## Priority

- [ ] Minor - typo, incorrect naming, fails on specific uncommon situation
- [x] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Information
**python version**: 3.10
**OS**: MacOS Monterey
**matplotlib version**: NA

## Example of the bug 

Occurs on `import pydarn` on new install. 

### Attempts

*What have you tried already to fix it?*
NA

*What have you tried to get around it?*
See above for solutions in the meantime. 

## Potential Bug Location 

On install during hdw repo cloning. 

## Potential Solution(s)

Any ideas welcome.

**Comment by ljlamarche** [comment]
I believe I've encountered this problem attempting to install pydarn in a clean conda environment.

```
>>> import pydarn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/e30737/miniconda3/envs/pydarn_test/lib/python3.10/site-packages/pydarn/__init__.py", line 51, in <module>
    from .utils.superdarn_radars import SuperDARNRadars
  File "/Users/e30737/miniconda3/envs/pydarn_test/lib/python3.10/site-packages/pydarn/utils/superdarn_radars.py", line 449, in <module>
    class SuperDARNRadars():
  File "/Users/e30737/miniconda3/envs/pydarn_test/lib/python3.10/site-packages/pydarn/utils/superdarn_radars.py", line 470, in SuperDARNRadars
    75, read_hdw_file('ade')),
  File "/Users/e30737/miniconda3/envs/pydarn_test/lib/python3.10/site-packages/pydarn/utils/superdarn_radars.py", line 109, in read_hdw_file
    get_hdw_files(force=update)
  File "/Users/e30737/miniconda3/envs/pydarn_test/lib/python3.10/site-packages/pydarn/utils/superdarn_radars.py", line 56, in get_hdw_files
    if len(os.listdir(hdw_path)) == 0 or force:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/e30737/miniconda3/envs/pydarn_test/lib/python3.10/site-packages/pydarn/utils/hdw/'
```

*Note:* I don't know if this matters at all, but I had to downgrade numpy (#295 ) to get to this error.
