### ISSUE TITLE
Install issue on leap 15.1 Borealis computer 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#57]
Trying to install pyDARN on open suse 15.1 via:
``` bash
pip3 install --user pydarn
pip3 install --user git+https://github.com/superdarn/pydarn
git clone https://github.com/superdarn/pydarn
cd pydarn
pip3 install --user .
python3 setup.py install --user 
```

All resulting in the same error with:
``` bash
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    'h5py', 'deepdish', 'pathlib2']
```
Last line in the error is:
``` bash
  File "/usr/lib64/python3.6/lib2to3/pgen2/grammar.py", line 108, in load
    d = pickle.load(f)
EOFError: Ran out of input
```

**Comment by mts299** [comment]
This might be  `pydarnio` issue now. Reopen if `pydarn` is needed.
